import { Product } from './types';

// Sample sneaker data for the store
export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Air Jordan 1 Retro High OG "Chicago"',
    brand: 'Nike',
    model: 'Air Jordan 1',
    size: 9,
    colorway: 'Chicago',
    condition: 'Excellent',
    price: 320,
    originalPrice: 170,
    description: 'The iconic Chicago colorway of the Air Jordan 1 returns in premium materials. Features the classic white, red, and black color scheme that Michael Jordan wore during his legendary 1985 season.',
    images: ['https://placehold.co/400x400/white/red?text=AJ1+Chicago'],
    releaseDate: '2022-09-17',
    category: 'Basketball',
    rating: 4.8,
    featured: true,
    inStock: true
  },
  {
    id: '2',
    name: 'Yeezy Boost 350 V2 "Zyon"',
    brand: 'Adidas',
    model: 'Yeezy Boost 350 V2',
    size: 10,
    colorway: 'Zyon',
    condition: 'New',
    price: 280,
    originalPrice: 220,
    description: 'The Yeezy Boost 350 V2 "Zyon" features a unique gradient effect on the Primeknit upper, transitioning from purple to pink. Equipped with responsive BOOST technology for comfort.',
    images: ['https://placehold.co/400x400/purple/white?text=Yeezy+Zyon'],
    releaseDate: '2023-04-29',
    category: 'Lifestyle',
    rating: 4.6,
    featured: true,
    inStock: true
  },
  {
    id: '3',
    name: 'Air Max 90 "Infrared"',
    brand: 'Nike',
    model: 'Air Max 90',
    size: 11,
    colorway: 'Infrared',
    condition: 'Good',
    price: 160,
    originalPrice: 130,
    description: 'The classic Air Max 90 in the iconic Infrared colorway. Features visible Air cushioning in the heel and a durable leather and mesh upper.',
    images: ['https://placehold.co/400x400/orange/white?text=AM90+IR'],
    releaseDate: '2021-06-12',
    category: 'Lifestyle',
    rating: 4.7,
    featured: false,
    inStock: true
  },
  {
    id: '4',
    name: 'Off-White x Nike Blazer Mid "All Hallows Eve"',
    brand: 'Nike',
    model: 'Blazer Mid',
    size: 8.5,
    colorway: 'All Hallows Eve',
    condition: 'Excellent',
    price: 420,
    originalPrice: 120,
    description: 'Virgil Abloh\'s Off-White collaboration with Nike on the Blazer Mid. Features deconstructed design elements, zip tie details, and the iconic Off-White aesthetic.',
    images: ['https://placehold.co/400x400/cream/black?text=OW+Blazer'],
    releaseDate: '2019-02-07',
    category: 'Lifestyle',
    rating: 4.9,
    featured: true,
    inStock: true
  },
  {
    id: '5',
    name: 'Dunk Low Retro "University Blue"',
    brand: 'Nike',
    model: 'Dunk Low',
    size: 10.5,
    colorway: 'University Blue',
    condition: 'New',
    price: 180,
    originalPrice: 100,
    description: 'The retro Dunk Low in University Blue returns with premium leather construction. Features the classic university blue and white colorway that pays homage to college basketball uniforms.',
    images: ['https://placehold.co/400x400/blue/white?text=Dunk+UB'],
    releaseDate: '2021-12-11',
    category: 'Basketball',
    rating: 4.5,
    featured: false,
    inStock: true
  },
  {
    id: '6',
    name: 'Air Force 1 \'07 "Triple White"',
    brand: 'Nike',
    model: 'Air Force 1',
    size: 9.5,
    colorway: 'Triple White',
    condition: 'Good',
    price: 110,
    originalPrice: 90,
    description: 'The timeless Air Force 1 in Triple White. Clean, versatile design with full-grain leather upper and encapsulated Air cushioning in the sole.',
    images: ['https://placehold.co/400x400/white/black?text=AF1+TW'],
    releaseDate: '2020-08-01',
    category: 'Lifestyle',
    rating: 4.4,
    featured: false,
    inStock: true
  },
  {
    id: '7',
    name: 'Air Jordan 4 Retro "Bred"',
    brand: 'Nike',
    model: 'Air Jordan 4',
    size: 12,
    colorway: 'Bred',
    condition: 'Excellent',
    price: 450,
    originalPrice: 200,
    description: 'The legendary Air Jordan 4 "Bred" returns with premium materials. Features the classic black and red colorway that Michael Jordan wore during the 1989 season.',
    images: ['https://placehold.co/400x400/black/red?text=AJ4+Bred'],
    releaseDate: '2022-02-12',
    category: 'Basketball',
    rating: 4.9,
    featured: true,
    inStock: true
  },
  {
    id: '8',
    name: 'Converse Chuck 70 Hi "Black"',
    brand: 'Converse',
    model: 'Chuck 70',
    size: 8,
    colorway: 'Black',
    condition: 'Fair',
    price: 75,
    originalPrice: 75,
    description: 'The upgraded Chuck 70 Hi features improved materials and construction compared to the original Chuck Taylor. Higher rubber foxing and softer canvas upper.',
    images: ['https://placehold.co/400x400/black/white?text=Chuck70'],
    releaseDate: '2017-01-01',
    category: 'Lifestyle',
    rating: 4.2,
    featured: false,
    inStock: true
  }
];

// Available filters for the store
export const availableFilters = {
  brands: ['Nike', 'Adidas', 'Converse', 'Jordan'],
  sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13],
  conditions: ['New', 'Excellent', 'Good', 'Fair'] as const,
  categories: ['Basketball', 'Lifestyle', 'Running'],
  maxPrice: 500
};